parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource:   "../src/*"
        exclude:    "../src/{DependencyInjection, Entity, Migrations, Tests, Kernel.php}"

    App\Api\Action\: # Todo lo que está debajo de esta  carpeta se considera un controlador
        resource: '../src/Api/Action'
        tags:   ["controller.service_arguments"]

    App\Api\Listener\JsonExceptionResponseTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }
